add product toevoegen
BAZandpoort/2dekans-veilingen-A pull request #45
Opened 2023-09-25 09:13 UTC by MohamedZP

2023-09-25 09:15 UTC, JurnGG requested changes
add colours to page

2023-09-25 09:20 UTC, nilsZP requested changes
verplaats addproduct naar sellerfunctions

2023-09-25 09:20 UTC, nilsZP commented on src/functions/userFunctions.php
> +function addProduct($connection, $naam, $beschrijving, $prijs, $categorie, $foto){
verplaats addproduct naar sellerfunctions

2023-09-25 09:41 UTC, nilsZP requested changes
add hover colour to submit button and error when file is not uploaded
maybe use #95B8D1
groetjes Jurn

2023-09-29 08:42 UTC, nilsZP approved these changes
mooi gedaan!

2023-09-29 08:47 UTC, JurnGG approved these changes
Looks good

2023-09-29 08:47 UTC, merged