Filters
BAZandpoort/2dekans-veilingen-A pull request #48
Opened 2023-09-29 12:46 UTC by programmeurGG

2023-09-29 13:50 UTC, nilsZP requested changes
add navbar to producten.php pls

2023-10-03 09:39 UTC, nilsZP requested changes
kort samengevat functies gebruiken aub

2023-10-03 09:39 UTC, nilsZP commented on src/index.php
> +            $result = $mysqli->query($sql);
gebruik een functie voor de categorieën te pakken

2023-10-03 09:39 UTC, nilsZP commented on src/producten.php
> +            $result = $mysqli->query($sql);
ook hier een functie aub

2023-10-03 09:39 UTC, nilsZP commented on src/producten.php
> +      $result = $mysqli->query($sql);
en als laatste hier een functie

2023-10-03 09:42 UTC, AbdelilahBZ commented on src/producten.php
> +      $result = $mysqli->query($sql);
ok, kga daar nu aan beginnen.

2023-10-06 12:58 UTC, closed without merging