Add aankoopgeschiedenis
BAZandpoort/2dekans-veilingen-A pull request #67
Opened 2023-10-06 14:25 UTC by JerkoJonckersZP

2023-10-08 17:32 UTC, JurnGG requested changes

2023-10-08 17:32 UTC, JurnGG commented on src/aankoopgeschiedenis.php
> +                    foreach (getAllPurchases($mysqli, $_SESSION['login']) as $row) {
Geef iets als er nog geen aankopen zijn.

2023-10-10 08:45 UTC, JurnGG requested changes

2023-10-10 08:45 UTC, JurnGG commented on src/aankoopgeschiedenis.php
> +    /*  SELECT tblproducten.foto, tblproducten.naam, MAX(tblboden.bod) AS highest_bid, tblgebruikers.voornaam, tblgebruikers.naam, tblfacturen.datum
Delete this

2023-10-10 09:27 UTC, JurnGG approved these changes
Make small change DLGTM!

2023-10-10 09:30 UTC, JurnGG requested changes
use component navbar

2023-10-12 14:50 UTC, nilsZP approved these changes
Het ziet er voor mij goed uit! Vraag zeker nog eens aan Jürn of hij het ook goed vindt.

2023-10-12 20:23 UTC, JurnGG approved these changes
Good job LGTM!

2023-10-13 08:43 UTC, merged