Bod
BAZandpoort/2dekans-veilingen-A pull request #70
Opened 2023-10-09 16:59 UTC by vichoutmeyerszp

Tja, opmaak moet nog gemaakt worden, maar wil al (hopen) te laten zien dat de code al werkt;

2023-10-09 20:22 UTC, JurnGG requested changes
Verbeter de design van bod.php of steek uw code in overzichtVeilingen.php

2023-10-09 20:22 UTC, JurnGG commented on src/bod.php
> +    echo "Error bij het toevoegen van je bod: Je hebt waarschijnlijk onder het minimum geboden. Ga terug en probeer snel opnieuw<br> ";
Stuur personen niet terug maar geef een error op uw pagina met daisyui layout

2023-10-09 20:22 UTC, JurnGG commented on src/bod.php
> +<!DOCTYPE html>
veranderen design om de layout van de website te matchen en add de navbar

2023-10-11 21:38 UTC, vichoutmeyerszp commented
Heb al basis layout toegevoegd aangezien ik niet echt weet wat jij goede layout vindt, geef gerust instructies dat het zeker tegen vrijdag af is

2023-10-12 15:46 UTC, vichoutmeyerszp commented
Zeg gewoon dat het nu gefixed is 😭 

Trwns jullie moeten zelf wel nog voor iedereen tblproducten updaten dat het decimals heeft (staat nu op 10.0 in plaats van 10.2)

2023-10-12 20:19 UTC, JurnGG approved these changes
good job LGTM!

2023-10-13 08:43 UTC, merged